<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE catalog
[
    <!ELEMENT catalog (product)>
    <!ELEMENT product (catalog_item+)>
    <!ATTLIST product product_id ID #REQUIRED description CDATA #REQUIRED product_image CDATA #REQUIRED>
    <!ELEMENT catalog_item (item_number,price,size+)>
    <!ATTLIST catalog_item gender CDATA #REQUIRED>
    <!ELEMENT item_number (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT size (color_swatch+)>
    <!ATTLIST size description CDATA #REQUIRED>
    <!ELEMENT color_swatch (#PCDATA)>
    <!ATTLIST color_swatch image CDATA #REQUIRED>
]>
<catalog>
  <product product_id="e4892f6a-7cce-11ec-90d6-0242ac120003" description="Cardigan Sweater" product_image="cardigan.jpg">
    <catalog_item gender="Men">
      <item_number>QWZ5671</item_number>
      <price>39.95</price>
      <size description="Medium">
        <color_swatch image="red_cardigan.jpg">Red</color_swatch>
        <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
      </size>
      <size description="Large">
        <color_swatch image="red_cardigan.jpg">Red</color_swatch>
        <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
      </size>
    </catalog_item>
    <catalog_item gender="Women">
      <item_number>RRX9856</item_number>
      <price>42.50</price>
      <size description="Small">
        <color_swatch image="red_cardigan.jpg">Red</color_swatch>
        <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
        <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
      </size>
      <size description="Medium">
        <color_swatch image="red_cardigan.jpg">Red</color_swatch>
        <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
        <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
        <color_swatch image="black_cardigan.jpg">Black</color_swatch>
      </size>
      <size description="Large">
        <color_swatch image="navy_cardigan.jpg">Navy</color_swatch>
        <color_swatch image="black_cardigan.jpg">Black</color_swatch>
      </size>
      <size description="Extra Large">
        <color_swatch image="burgundy_cardigan.jpg">Burgundy</color_swatch>
        <color_swatch image="black_cardigan.jpg">Black</color_swatch>
      </size>
    </catalog_item>
  </product>
</catalog>